# Generated by Django 5.1.5 on 2025-01-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('email_1', models.EmailField(max_length=254, unique=True)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('attendance_count', models.IntegerField(default=0)),
            ],
        ),
    ]
