# Generated by Django 5.1.5 on 2025-01-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochadzka_app', '0002_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='player',
        ),
        migrations.AddField(
            model_name='training',
            name='player',
            field=models.ManyToManyField(to='dochadzka_app.player'),
        ),
    ]
