# Generated by Django 5.1.5 on 2025-01-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochadzka_app', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='all_training_count',
            field=models.IntegerField(default=0),
        ),
    ]
