# Generated by Django 5.1.5 on 2025-01-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochadzka_app', '0005_player_all_training_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='category',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='training',
            field=models.ManyToManyField(to='dochadzka_app.training'),
        ),
    ]
