# Generated by Django 5.1.5 on 2025-01-30 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochadzka_app', '0006_rename_category_training_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='training',
        ),
        migrations.AlterField(
            model_name='training',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dochadzka_app.category'),
        ),
    ]
