# Generated by Django 5.1.5 on 2025-01-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochadzka_app', '0007_remove_category_training_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='training',
            field=models.ManyToManyField(to='dochadzka_app.training'),
        ),
        migrations.AlterField(
            model_name='training',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
