# Generated by Django 5.1.5 on 2025-01-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochadzka_app', '0008_category_training_alter_training_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='category_name',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='training',
            field=models.ManyToManyField(related_name='categories', to='dochadzka_app.training'),
        ),
    ]
