# Generated by Django 5.1.5 on 2025-01-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dochadzka_app', '0009_rename_category_name_training_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
