# Generated by Django 5.1.5 on 2025-02-02 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochadzka_app', '0010_rename_name_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='player',
        ),
        migrations.RemoveField(
            model_name='category',
            name='training',
        ),
        migrations.RemoveField(
            model_name='category',
            name='year',
        ),
        migrations.RemoveField(
            model_name='training',
            name='player',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Neznáma kategória', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='categories',
            field=models.ManyToManyField(related_name='players', to='dochadzka_app.category'),
        ),
        migrations.AddField(
            model_name='training',
            name='players',
            field=models.ManyToManyField(related_name='trainings', to='dochadzka_app.player'),
        ),
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='dochadzka_app.category'),
        ),
    ]
