# Generated by Django 5.1.5 on 2025-02-04 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochadzka_app', '0011_remove_category_category_name_remove_category_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dochadzka_app.player')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dochadzka_app.training')),
            ],
        ),
    ]
